export default {
  PENDING: "PENDING",
  WAITING_PAY: "WAITING_PAY",
  WAITING_SHIPPER: "WAITING_SHIPPER",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",

  //deprecated
  FINDING_SHIPPER: 1,
  SHIPPING: 4,
  DONE: 5,
  CANCELED: 6,
};
