export default {
  PENDING: "PENDING",
  WAITING_PAY: "WAITING_PAY",
  FOUND_SHIPPER: "FOUND_SHIPPER",
  CONFIRM_WITH_CUSTOMER: "CONFIRM_WITH_CUSTOMER",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",

  //deprecated
  FINDING_SHIPPER: 1,
  SHIPPING: 4,
  DONE: 5,
  CANCELED: 6,
};
