export default {
    ONBOARDING: 'On boarding',
    HOME: 'Home',
    LOGIN: 'Login',
    REGISTER_NAVIGATE: 'Register navigate',
    CHOOSEACCOUNT: 'Choose Account',

    BASIC_INFO_REGISTER: 'Basic info register',
    ACCOUNT_REGISTER: 'Account Register',
    CONFIRM_OTP_REGISTER: 'Confirm otp register',
    DRIVER_INFO_REGISTER: 'Driver info register',
    AVATAR_REGISTER: 'Avatar register',
    COMPELETE_REGISTER: 'Complete register',

    HOME_DRAWER: 'Home Drawer',
    WALLET_DRAWER: 'Wallet Drawer',
    ORDER_DRAWER: 'Order Drawer',
    PROFILE_DRAWER: 'Profille Drawer',
    NOTIFICATION_DRAWER: 'Notification',
    REVIEW_ORDER_DRAWER: 'Review order drawrer',
    SEARCH_ORDER_DRAWER: 'Search order drawer',
    VNPAY_WEBVIEW_DRAWER: 'VNPAY',

    HOME_STACK: 'Home Stack',
    MAP_STACK: 'Map Stack',
    ADDRESS_INPUTER_STACK: 'Address Input Stack',
    MORE_ORDER_DETAIL_STACK: 'More Order Detail Stack',
    ORDER_DETAIL_STACK: 'Order Detail Stack',
    ADD_COMMENT_FOR_COURIER_STACK: 'Add comment for courier stack',
    ORDER_STATUS_STACK: 'Order Status Stack',
    VIEW_FEEDBACK_STACK: 'View Feedback Stack',

    DRIVER_NAVIGATION: 'Driver navigation',
    HOME_DRIVER_TAB: 'Home driver tab',
    ORDER_DRIVER_TAB: 'Order driver tab',
    WALLET_DRIVER_TAB: 'Wallet driver tab',
    NOTIFICATION_DRIVER_TAB: 'Notification driver tab',
    FIND_ORDER_DRIVER_TAB: 'Find order driver tab',
    PICK_ORDER_DRIVER_TAB: 'Order detail driver tab',
    REVIEW_ORDER_DRIVER_TAB: 'Review order driver tab',
    SEARCH_ORDER_DRIVER_TAB: 'Search order driver tab',

    DRIVER_PROFILE_NAVIGATION: 'Driver profile navigation',
    DRIVER_PROFILE_STACK: 'Driver profile stack',
    DRIVER_SETTING_STACK: 'Driver setting stack',
    DRIVER_CHANGE_PROFILE_STACK: 'Driver change profile stack'
}